### ISSUE TITLE
Projeto Completo

### ISSUE THREAD

**Issue by GuiSM6030** [VitorSantiago232/Projeto03-2024#1]
**Funcionalidades**
- [x] Adicionar até 255 contatos
- [x] Listar todos os contados _(não é necessário salvar em arquivo texto)_ #6
- [x] Deletar contato escolhido usando o número de telefone #7
- [x] Salvar agenda em arquivo binário #8 
- [x] Carregar agenda do arquivo binário #9

**Comment by GuiSM6030** [comment]
**As funções foram adicionadas, falta adicionar os 255 contatos pra deixar salvos**

**Comment by VitorSantiago232** [comment]
Minha parte está 100% concluída, favor fazer a de vocês com urgência!

**Comment by VitorSantiago232** [comment]
Tirei a dúvida com o professor e não precisamos adicionar 255 contatos manualmente, pois ele deseja somente o espaço de armazenagem!
